name: CICD Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'ess-eng'

jobs:

  upload-aem-package:    
    uses: Faazil/aem-common-build/.github/workflows/main.yml@main  
    with:  
      AEM_ENV: ${{ github.event.inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
